### ISSUE TITLE
javascript-sandbox-start folders

### ISSUE THREAD

**Issue by apsolut** [bradtraversy/javascript-sandbox#1]
Noticed: 

1. `javascript-sandbox-start`  folders stops at `15-nodejs-modules`
2. `8,9` should be `08, 09` just to be unified

**Comment by bradtraversy** [comment]
Thanks, I did fix the numbering, however, I had them stop there because the start files are only for the learning modules and not the projects. The projects have the starter code in their respective sections in the course.
